sudo: required
dist: trusty
language: node_js
before_install:
- curl https://install.meteor.com | /bin/sh
- export PATH="$HOME/.meteor:$PATH"
script:
- meteor build $HOME/build.tgz
deploy:
  provider: modulus
  api_key:
    secure: ubSMp3FQq6kMqFmXTuNFeCEVMVNTg/rM3FOfOKBS7MRNg9wE7UAPLykJ2t1Bbt86NuSSy8iNxZiyw7IiGLRZQR3gDCKARvgwJekiMwDjXxPWPDJBBGGiMkoKs2HBSMca55Gx5V8rqshX60DoOXxoeguS8XyZHQADgYGZ5s21NVcydnsXx+WnQ8cdHuJROg2ixsfvB8xLudlnWSG3BN8ijGdL8z4cLHC9FH3YVhRPxfhV4sQeAjfFYmzAou+eSQRFGIo93ufPlUtKP4QVyIed7fd9gykJnYe+RI10noFUR/+UCW/wxYoavbATGmqtfJQNZkmPs0kPpYTh4JJ146KRDpCLMnWpgn44PNMX4+uAWttPqcnru757Bk5fZXcy1B8bYtbp5W5TvPBRIQpNEUILQ+80pqTXk36F1cohrOp3/0LDmuM4J2qahF511r29VPqQzwAozeGajNIxdsiiVbbfyPckfrxGTvYu7HU1LirRLqOpPH4aq1It9W82iBgAjQWZvb/ECyerQJfm1Yx/oj5fW9Hl5rcDXiP1oefY/QULmnSvMR30M7clR3vexeULN+PozzrRKyFCMvVPL2i9uOaBuabtKyMk9KWPUPYzUE2gSBTfnxNCb5g3RkGSnm3y5HAdjeOy9CDLowYL4d9KC4kUscAYB8Md62kx7USGs0k8U9I=
  project_name: EVSD
  key:
    secure: PBsz04kwuKKiDyY8TJjuEV5yKlxwApJqBayekbCwYSvnzwJoNPx9l0LCpch625cazp+KfQKBVgWkP2DP43INW4ISoSktWhm0gViCGVNWQidEyDwXA+gAeHpD3+SHIVJcltEQwDzQQfjI9KnAODdtudIjq+9NqfA9aWsVBt1PVqXozl9OnPgnvpDiARRb+ym0l0PjRZidNqEBFJ/6im/qGm0vN6G/XMV+3J5omwYM5cuKlULKfMit4CethORgtN9pA4WAJqKJMrNm2u04/NWY1XX4FsZXtNJW0LLfbtdlEpd5FxuT0EdJebbwyuqK4Pf8oGcEz4Wo1zGO5uSv24ae9QiJQi52eBcdrGw70jhOjbTmxFa1rHWRT1ORhOLuIvOsTcfoUxgXtcIjA/5Arntp4KSBLXX0NDzxPvIr/2fPX+L4X4XA5pRMXxMKt5Rh3Q/srKb7HLH/6yU5mgCvzFr+HlVKqZq4ePYBDV28n65kihca1gby5G1Tx2cjHlkeNhe+ukkRNBXQ/WbORUKVF8XUSPnz0Rrx/7Rl4SfaQg5TyJFigtvCQveHkYCekdsnXP7OgrqOY7bxepwRwyLI2UJRpb+prY+Qes1Tyg6u99ckXPsR6s/5OLXfDPOvudU12FlEApQ7QJDcgWehQDSt6l/F+ln8op6TomVRn1H0uKdDGos=
