sudo: true

language: node_js

before_install:
 - curl https://install.meteor.com | /bin/sh
 - export PATH="$HOME/.meteor:$PATH"

script:
 - meteor build $HOME/build.tgz

deploy:
  provider: modulus
  api_key:
    secure: g3ff9sssv99JF90cwQrtkTjykeCpt/Fcv6JS6Jx2+olOdkwQNDp0Yn2ilPLF2g2TzPoE6yO21wMdMEqX/O3jvm774pIYiuegkYj4Wl7ortyuwyoQOjqX8GhYfNr6j17YfdAiGVwlM7rQjKBJCgJmkH9Q3AG4JrIg2phFzoUZWLrNTkQiW1Y3JdMAhRNoFh0l9NqAKaF8RMoAvaEDKhLyuzw+E4T4w+lxsGfZGmFsAyEM9D9KK0m1RHdJQtZeqUnVsKhJIRPVVvnnhhE6QEtPCO3387SbYU2TP/lZFqBO3BmZEGYqj1n2UXnQjtdPEUz6yvhOLveSReJCE/5tMCIBrZd5T8+bGTs7HSx5PDDsHy4VXA3668IKl3n6/kaN3Jpe0HAsKvZRNOgX3/7BNnU0+Bj1iZwybgcFuIVKtdSeWRNwX1evaxZ8mSNA+UPXulOIVm5IG/sSzC2DbUA9uocQ2GMFPD7+AsqZ4+9kdtSxKkm/Uudx7gtz5+ynFMCGzwm68MpZ0PmeclV/B4PiBboohtzMpzDUTmY/CuBMvxSJdp2/lWo1dv2pUO7kIpR3STaI5cs6vXw3r/9Qv1iXmKtcqcvCbRKrn7a53YxzzF/fLVOB468WOo6tFULt02lcQKjHTGurM5U8MfNCivM+1KnG91QjfLYSoJdlyqoIp5NHU1c=
  project_name: EVSD