sudo: required
dist: trusty
language: node_js
before_install:
- curl https://install.meteor.com | /bin/sh
- export PATH="$HOME/.meteor:$PATH"
script:
- meteor build $HOME/build.tgz
deploy:
  provider: modulus
  api_key:
    secure: PBsz04kwuKKiDyY8TJjuEV5yKlxwApJqBayekbCwYSvnzwJoNPx9l0LCpch625cazp+KfQKBVgWkP2DP43INW4ISoSktWhm0gViCGVNWQidEyDwXA+gAeHpD3+SHIVJcltEQwDzQQfjI9KnAODdtudIjq+9NqfA9aWsVBt1PVqXozl9OnPgnvpDiARRb+ym0l0PjRZidNqEBFJ/6im/qGm0vN6G/XMV+3J5omwYM5cuKlULKfMit4CethORgtN9pA4WAJqKJMrNm2u04/NWY1XX4FsZXtNJW0LLfbtdlEpd5FxuT0EdJebbwyuqK4Pf8oGcEz4Wo1zGO5uSv24ae9QiJQi52eBcdrGw70jhOjbTmxFa1rHWRT1ORhOLuIvOsTcfoUxgXtcIjA/5Arntp4KSBLXX0NDzxPvIr/2fPX+L4X4XA5pRMXxMKt5Rh3Q/srKb7HLH/6yU5mgCvzFr+HlVKqZq4ePYBDV28n65kihca1gby5G1Tx2cjHlkeNhe+ukkRNBXQ/WbORUKVF8XUSPnz0Rrx/7Rl4SfaQg5TyJFigtvCQveHkYCekdsnXP7OgrqOY7bxepwRwyLI2UJRpb+prY+Qes1Tyg6u99ckXPsR6s/5OLXfDPOvudU12FlEApQ7QJDcgWehQDSt6l/F+ln8op6TomVRn1H0uKdDGos=
  project_name: EVSD
  