sudo: required
dist: trusty
language: node_js
before_install:
- curl https://install.meteor.com | /bin/sh
- export PATH="$HOME/.meteor:$PATH"
script:
- meteor build $HOME/build.tgz
deploy:
  provider: modulus
  api_key:
    secure: ubSMp3FQq6kMqFmXTuNFeCEVMVNTg/rM3FOfOKBS7MRNg9wE7UAPLykJ2t1Bbt86NuSSy8iNxZiyw7IiGLRZQR3gDCKARvgwJekiMwDjXxPWPDJBBGGiMkoKs2HBSMca55Gx5V8rqshX60DoOXxoeguS8XyZHQADgYGZ5s21NVcydnsXx+WnQ8cdHuJROg2ixsfvB8xLudlnWSG3BN8ijGdL8z4cLHC9FH3YVhRPxfhV4sQeAjfFYmzAou+eSQRFGIo93ufPlUtKP4QVyIed7fd9gykJnYe+RI10noFUR/+UCW/wxYoavbATGmqtfJQNZkmPs0kPpYTh4JJ146KRDpCLMnWpgn44PNMX4+uAWttPqcnru757Bk5fZXcy1B8bYtbp5W5TvPBRIQpNEUILQ+80pqTXk36F1cohrOp3/0LDmuM4J2qahF511r29VPqQzwAozeGajNIxdsiiVbbfyPckfrxGTvYu7HU1LirRLqOpPH4aq1It9W82iBgAjQWZvb/ECyerQJfm1Yx/oj5fW9Hl5rcDXiP1oefY/QULmnSvMR30M7clR3vexeULN+PozzrRKyFCMvVPL2i9uOaBuabtKyMk9KWPUPYzUE2gSBTfnxNCb5g3RkGSnm3y5HAdjeOy9CDLowYL4d9KC4kUscAYB8Md62kx7USGs0k8U9I=
  project_name: EVSD
